export const EVENT_CREATE_REQUEST = "EVENT_CREATE_REQUEST"
export const EVENT_CREATE_SUCCESS = "EVENT_CREATE_SUCCESS"
export const EVENT_CREATE_FAIL = "EVENT_CREATE_FAIL"

export const EVENT_GET_REQUEST = "EVENT_GET_REQUEST"
export const EVENT_GET_SUCCESS = "EVENT_GET_SUCCESS"
export const EVENT_GET_FAIL = "EVENT_GET_FAIL"